#!/bin/sh
cd /var/www/
cp .env.example .env
chmod -R 777 storage
composer install
php artisan migrate
php artisan key:generate
php artisan jwt:secret
php artisan cache:clear
php artisan config:clear

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"